# logger = logging.getLogger(__name__)  # there might not be a whole lot to log on this tab.
import gradio as gr
# import logging


with gr.Blocks() as about:
    # with gr.Sidebar(position = "left", open = False) as sidebar:
    #     logout = gr.Button("Logout", link = "/logout")

    title = gr.Markdown("# About")
    chatbot = gr.Markdown("The chatbot provides a simple interactive way to find and reference the rules. Using a combination of Ollama (Phi4 for the model), LangChain (qwen3 for the embedding model), and ChromaDB, along with PDF Plumber, various rule books can be uploaded and stored for later reference. One challenge with this is the table nature of RPG books: they store a lot of important information in tables, and so adjusting both the chunk size and the chunk overlap is an important part of uploading any data.")
    upload = gr.Markdown("Uploading documents is fairly easy, however there is an art to properly ingesting a file. Due to how RPG rulebooks use so many tables, pictures, odd fonts, etc. it's not a one-size-fits-all for every document. By default the document is sliced every 4000 words, with a 200 word overlap, but this can be adjusted when the document on the upload page. It is important to audit the document after ingestion: make sure that the chatbot can properly retrieve the data. If it cannot, there is a button to delete documents.")
    copyright = gr.Markdown("No games are provided by default. You have to build your own database. This will take time based on your system capabilities.")
    # copyright = gr.Markdown("There are a few games provided here by default. Those games are: Enchanted Realms and Super Hero Fun (both in Public Domain), and Codename: Spandex (which is under creative commons. Also this is a clone of Squadron UK, so if you like C:S check out that one.)")
    
    with gr.Accordion(label = "Instructions", open = False) as instructions:
        gr.Markdown("The chatbot works by taking advantage of Ollama. As a result you bring you own model to the system. As long as Ollama can list it, it can be used, so chatbots outside of Ollama are also acceptable. However, since you bring your own Language Model, both its response time and quality of responses are based on the model you bring and the system you have. Multiple models can be used, and can be switched between. Switching between models between chats however can have unintended consequences. As of 6/8/26, chat cannot be auto saved, but it can be copied and manually saved into a file of your choice if you wish.")
        gr.Markdown("When looking for a response, the model will try to investigate the user message for metadata tags, the name of the rule system, and if the question is a specific question or a generalized one. The metadata tags will be used to search the vector database for relevant information, and will additionally filter by rule system. Both of these can be manually used in the 'Options' menu. A drop down menu of the available documents is also there, but is for reference only.")
        gr.Markdown("Advanced options in the chatbot area allow for the choice of the language model and the embedding model (see the Database section for information on how that is used), and the ability to adjust the Top K Queries and the similarity threshold of the search. By default they are set to 10 and 0.3 respectively.")
        gr.Markdown("A comment on cosine similarity.\nCosine Similarity is normally just the angle between two vectors, with a range of values as [-1, +1]. ChromaDB does an extra step, and measures 1 - [cosine similarity], which changes its range of values to [0, 2]. Whereas in normal cosine similarity -1 means 'exact opposite' and +1 means 'totally similar', ChromaDB's range of values are interpreted as 0 being 'totally similar' and 2 being 'exact opposite.' By default Technomancer, using the ChromaDB scale (which is just a conversion from one range of values to another, it doesn't actually change the underlying mathematics), uses 1 as its default similarity score threshold. This can be adjusted on the Chatbot tab.")
        gr.Markdown("## Important note about ingestion")
        gr.Markdown("Due to how PDFs are designed, particularly in the RPG community, they use a lot of stylized fonts, images, and layouts. This makes reliably ingesting a book a bit of an art. There are *no guarantees* that a book will be properly ingested. There is a database tab to see how the document was ingested, and a lot of work has been put into making it as reliable as possible, but it is possible that not every situation has been addressed.")
        
    with gr.Accordion(label = "Suggestions for LLMs", open = False) as suggestions:
        gr.Markdown("Because this is BYOLLM (bring your own LLM), and the choices can be overwhelming, here are some suggested ones:")
        gr.Markdown("Pretty much any embedding model can be used, but nomic-embed-text (https://ollama.com/library/nomic-embed-text) and mxbai-embed-large (https://ollama.com/library/mxbai-embed-large) were used when testing and designing Technomancer and had great success at vectoring and retrieving information. They are fairly small, but they are quick to vectorize the information.")
        gr.Markdown("For a language model for summary and retrieval, Phi4 (https://ollama.com/library/phi4) had the most success at pulling information, not reinterpreting rules, not making up information when retrieval failed, and citing the proper pages. It is ~10 gigs, so it's not small. Phi4-mini was not tried. One problem that was repeatedly found was that LLMs always try to answer a question, even if they don't have an answer, and some are trained to be more narrative generating rather than reporting. Ones that generate narrative try to inject information and content that is not relevant to the question, and ones that try to find an answer often generalize rules and content from other systems, often in ways that are not applicable. For the Language Model you want something almost academic in its reading of the text.")
        gr.Markdown("For the Vision model, minicpm-v was used for testing the Multimodal system (https://ollama.com/library/minicpm-v). Vision models can be quite large, and minicpm-v had a nice trade off between being small and powerful enough for the demands of Technomancer: minicpm-v is designed to run on mobile devices.")

    with gr.Accordion(label = "Uploading", open = False) as upload:
        gr.Markdown("To add a document to the database:")
        gr.Markdown("First choose a rule system. If the one you want is not present, then you can type it in and press 'Add Rule System'. A collection will be added to ChromaDB for documents to be added to that system. Additionally, metadata tags can be added to the document. Clicking 'Save Tags' saves them to an external yaml file for use in additional documents. It is best to add metadata and to be consistent in adding metadata to all documents. Technomancer also will try to dynamically add additional metadata tags to the documents, and will add them based on the text it finds (more on that in the Log and Settings section). A note about collection names: they are converted to an ASCII decimal representation with _ separating the ASCII numbers (Example becomes 69_120_97_109_112_108_101). This should all happen under the hood, so you'll never know it's there. This is done because the collection needs to be <512 characters long and end on a number of lower case letter. Instead of creating a wide variety of ways to clean whatever the user inputs as the collection title, it is changed to ASCII decimal, ensuring it is only numbers and underscores, and the final part is a number. This does elongate the rule system name, so keep collection names <120 letters to be safe.")
        gr.Markdown("Documents in the database are chunked, and the size of the chunks is adjustable. It is not a one size fits all solution. Larger chunk size make for quicker ingestion, but can miss critical information. Smaller chunk size gives very specific information, which can be too specific. Additionally the chunk overlap is adjustable, though it will auto snap to 10/% of the Chunk Size. The summary chunk size is for the large scale ingestion of the document. Technomancer uses Hierarchial Indexing, and will combine several smaller chunks to create a larger one for generalize summaries. The summary chunk option allows you to adjust how large that is. By default it is 10 chunks that are combined. The Chunk batches is to batch ingest the files, which helps save memory by only ingestion a few chunks at a time. Smaller batches takes longer but uses less memory, while larger batches are faster but take up more memory.")
        gr.Markdown("The embedding model can be adjusted, along with the language model that will be used to generate the summary from the larger chunks.")
        gr.Markdown("To ingest a file, once the embedding model has been chosen, the rule system set, the metadata (if any) has been tagged, and the chunks adjusted, a file can be uploaded. This will take a significant amount of time as the document will effectively be ingested twice, once as a series of summaries, and once as a series of chunks. However this only needs to be done once.")
        gr.Markdown("Metadata is dynamically added to each chunk based on the contents of that chunk. A set of keywords and what metadata tags they correspond to are in the Settings folder in the 'EnrichTags.toml' file, which can be edited to add or subtract tags from.")
        gr.Markdown("A file can either have its chunks saved, the summary saved, or both. By default both are saved, and if 'Both' is chosen, this will override other options (i.e. checking Chunks and Both saves Both). Summaries can be regenerated later.")
        gr.Markdown("Each chunk is scored, which then determines if the chunk is passed into the main database or into quarantine. The quarantined database is for chunks that the LLM had trouble reading because the fonts were odd, it was rotated to much, little text was pulled, etc. These chunks can be healed in the database tab.")

    with gr.Accordion(label = "Database Management", open = False) as db:
        gr.Markdown("This section also allows for management of the database: additional metadata can be added to a document if something wasn't fully tagged, and a document can be deleted. Additionally a whole rule system can be deleted, books and all.")
        gr.Markdown("Individual chunks can be retrieved here for inspection. This allows the user to see what was ingested and with what quality. Some documents, due to their stylistic choices, are harder to ingest then others: rotated images that contain font, unusual typeface, etc. all make ingestion harder. A document can contain thousands of chunks after being ingested, but this allows for manually editing them all. Chunks can also have individual metadata tags edited (either added or removed).")
        gr.Markdown("The summary can be regenerated, which removes the original summary and starts over. The number of chunks used in a single summary can be adjusted here as well.")
        gr.Markdown("Individual chunks, entire documents, and entire rule systems can be deleted here.")
        gr.Markdown("Healing of chunks can be done here. ")

    with gr.Accordion(label = "Logs and Settings", open = False) as logs:
        gr.Markdown("Logs can be viewed here: simply select a log and the textarea will populate with the contents live. Additionally the log can be found in the 'Logs' folder.")
        gr.Markdown("Outside of the logs there is a 'Settings' folder, which currently uses .yaml files to save various default settings and options. .yaml files are human readable and easily editable, so for those users who wish to make adjustments can. For example, a Keyword.yaml file provides a way for Technomancer to dynamically add metadata to documents: it will scan a chunk for certain key words and tag that chunk with the appropriate metadata. Feel free to add additional words to those categories, and to add more categories.")
        gr.Markdown("To sort between Embedding Models and Language Models, a non-comprehensive list of embedding models is here: this can be added to or removed, however removing it will prevent Technoamncer from listing any embedding models, essentially breaking the app.")

    with gr.Accordion(label = "Login System", open = False) as login:
        gr.Markdown("Technomancer has small login system. This works as a local server, allowing multiple users to login in. However it is not meant as a larger web portal, as there is no serious security built into it: use this on a local network *only*. If you wish to have more serious security, you can look into that, but it will not be supported.")
        gr.Markdown("There is a wealth of information about this if you wish to add your own login. Again, this will not be supported and you are on your own.")

    # note_embedding = gr.Markdown("## Note about embedding model names")
    # note_embedding_note = gr.Markdown("This will auto detect and sort your models by language and embedding models. This ASSUMES your embedding model is in the list of models found the in the Settings folder. If it is not, please add it and restart Technomancer.")
    # metadata = gr.Markdown(" For example, a group might be playing D&D 5e, but with home brew rules, and wants to pull up the grappling rules they wrote. Instead of getting the having to make several collections, sometimes with the same information, they can simple ask Technomancer about the grapple rules in their homebrew game, and Technomancer can search for both vanilla rules and homebrew ones.")

print("Rendered About page")

if __name__ in "__main__":
    about.launch()